version: '3.6'

services:
  redis:
    image: redis:alpine
    volumes:
      - cache:/data

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=boiler
      - POSTGRES_PASSWORD=bo1lerplate
      - POSTGRES_DB=boiler
    ports:
      - '54323:5432'
    volumes:
      - db:/var/lib/postgresql/data

  db-test:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=boiler
      - POSTGRES_PASSWORD=bo1lerplate
      - POSTGRES_DB=boiler-test
    ports:
      - '54324:5432'
    volumes:
      - db-test:/var/lib/postgresql/data

  celery:
    stdin_open: true
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    command: celery worker -A app.worker.celery -l DEBUG --beat
    depends_on:
      - redis
      - db
      - db-test
    env_file:
      - ./api/.flaskenv
    volumes:
      - ./api:/api
      
  api:
    stdin_open: true
    tty: true
    build:
      context: ./api
      dockerfile: Dockerfile
    command: flask run -h 0.0.0.0 -p 6000
    depends_on:
      - celery
    ports:
      - '6000:6000'
    env_file:
      - ./api/.flaskenv
    volumes:
      - ./api:/api

volumes:
  db:
  db-test:
  cache:
